package requester

import (
	"fmt"

	"github.com/dchest/siphash"
)

// Code adapted from github.com/cornelk/hashmap
// Under the Apache 2.0 license:
// https://github.com/cornelk/hashmap/blob/33e58823eb9d4426a8d2b604cece33c3c15df8cc/LICENSE
const (
	// generated by splitting the md5 sum of "hashmap"
	sipHashKey1 = 0xdda7806a4847ec61
	sipHashKey2 = 0xb5940c2623a5aabd
)

func complexKey(s string, b []byte) string {
	return fmt.Sprintf("%s+%x", s, siphash.Hash(sipHashKey1, sipHashKey2, b))
}
